### ISSUE TITLE
github-wide with Octotree sidebar

### ISSUE THREAD

**Issue by nobe0716** [mdo/github-wide#58] opened 2019-01-23 03:23 UTC
Hello, 

I found this repo today, and it gives me quite a good wide view on github. 👍👍👍 

Since I use [octotree](https://github.com/ovity/octotree) plugin, 
which show me code tree on steroids.
It has very small conflicts with github-wide.

![image](https://user-images.githubusercontent.com/5964919/51580545-3c194800-1f08-11e9-9e95-9e610a9809cf.png)

As you see, navbar by octotree hide content of issue.
I want to move .repository-content  depends on navbar width but I don't know about css very well 😢 
May I get a advice for this issue?

thanks

**Comment by cfoellmann** [comment] 2019-01-23 08:48
I tested the code with and without your change.
I could not reproduce your problem with the "old" code and it does not change the behavior with the change. 🤷‍♂️

**Comment by nobe0716** [comment] 2019-01-23 10:16
@cfoellmann 

I noticed that it does not have any problem with current github.com 😮 

I guess this may happen in a prticular version. 🤔 
My company use Github Enterprise 2.14.8.

![image](https://user-images.githubusercontent.com/5964919/51599243-7acbf400-1f42-11e9-9bc6-042177316f09.png)

**Comment by cfoellmann** [comment] 2019-01-23 10:19
I see what you mean.
Since this does not have negative effects it should be merged.

**Closed** 2019-02-19 21:23 UTC

**Comment by hovissimo** [comment] 2019-06-17 18:54
I reproduced this issue with the PR review page `https://github.com/[account]/[project]/pull/[id]` but I couldn't reproduce when I made a new public PR to file an issue with.

I found out that sometimes I need to refresh Github to get github-wide to come out from under octotree /shrug.  Up to the maintainer to care, or not.  Thanks for github-wide!
